language: node_js
node_js:
- node
install:
- npm install
script:
- npm run lint
- npm test -- --browsers=PhantomJS --watch=false
deploy:
  provider: heroku
  api_key:
    secure: KlQEnzrRQ9I6ro5EG0r0lILYDXXMTCrvsA/wn8wpnaSnNyINs4LLSyyFFhsTylMA6UyjmOFx0FDrlU+iojaQ4ZUFfgml5ncuj5viWpwDg1pduTdIE/5ocZvE2yzqCdeUGgo5qwuV3M7OUg0MhzDU1sG3WH0Dr1rwUzDnsN0QoTVcHdvo8+gNg34LPaPWs5FVLOPT11jpfrdSZxdPCPng1wvB+ZHZN040u8rS1p8VeLv7/OkZQDnogms4va3UM7ueOiWiSWxz+1Hu06XLY5VTnAKjAqafQkrAHr+HrzOCN5L5DDXZ29Iavf+gtvHQUsUbp3eEW1tgayfklcWlraIgMqnZ77cPNPkqrcdwbR+6HbSGqcWQ2WR9vI9QIRxBgMi1TdF5xXLh/UWLGuLj9qMNtP4I5GlBS9HgwVtSaw/kWCF0X2hbTKzAFTsDncBmJUFv+0CuY08FRMKOImzweXxzvtKP8dxWmVTVZvPhGlNRvheqIfJSsZgF5Z/a8lkluXHiczxND/nobEk6dHCUN8mPDuz9VroqcrYhPTajTVP7eSYu48sBMxQgpUJ9L8HWo2q0548JMH2VJ7PattbpAUDufYFg0jwTKs0TPrkCBUvWJpYlfZNyoUiQlIpo+MsKGF9IboNaNpzjxrbaya41KQyXa8nhuWPDGtRU3kek0lG7Few=
  app: dfsmvp
